version: "3.8"
services:

  # GOFIBER_API
  gofiber_server:
    build:
      context: ./fiber_server
      dockerfile: ./Dockerfile
    container_name: gofiber_server
    image: gofiber_server:tag
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${GOLANG_PORT}:${GOLANG_PORT}
    depends_on:
      - db
    links:
      - db
    expose:
      - ${GOLANG_PORT}

  # POSTGRES_DATABASE
  db:
    container_name: db
    image: "postgres:latest"
    restart: always
    ports:
      - ${HOST_PORT}:${HOST_PORT}
    volumes:
      - postgres-pgdata:${PGDATA}
    expose:
      - ${HOST_PORT}
    env_file:
      - .env

volumes:
  postgres-pgdata:
    driver: local
    # define the name of the volume, so that it wouldn't change when the folder of the project changes
    name: pgdata
