// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"time"
)

type Post struct {
	PostID    int64     `json:"post_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	PostTitle string    `json:"post_title"`
	PostBody  string    `json:"post_body"`
	UserID    int32     `json:"user_id"`
}

type User struct {
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
}
